[package]
name = "rdfs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
thiserror = "2.0.16"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "master"
path = "src/bin/master.rs"

[[bin]]
name = "storage"
path = "src/bin/storage.rs"

[[bin]]
name = "client"
path = "src/main.rs"

[[bin]]
name = "client_demo"
path = "src/bin/client_demo.rs"
